// <auto-generated />
namespace PrescriptionDataManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddPrescriptionController : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPrescriptionController));
        
        string IMigrationMetadata.Id
        {
            get { return "202008171334319_AddPrescriptionController"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
